"""
GitHub search results loader — Load pre-scraped repos from SEART-GHS exports.

This module replaces direct GitHub API searching. Instead, repositories are
discovered from pre-exported CSV files generated by https://seart-ghs.si.usi.ch/

RATIONALE
=========
Using SEART-GHS provides:
  - Reproducibility: Fixed, known set of repositories
  - Consistency: All repos filtered with identical criteria
  - Efficiency: No need to interact with GitHub API
  - Academic rigor: Published dataset, citeable source

EXPECTED DIRECTORY STRUCTURE
=============================
github-search/
  ├── python-results.csv.gz
  ├── python-results.json.gz
  ├── java-results.csv.gz
  ├── java-results.json.gz
  ├── javascript-results.csv.gz
  ├── javascript-results.json.gz
  ├── typescript-results.csv.gz
  └── typescript-results.json.gz

Each CSV follows SEART-GHS output format with columns:
  id, name, isFork, commits, branches, releases, forks, mainLanguage,
  defaultBranch, license, homepage, watchers, stargazers, contributors,
  size, createdAt, pushedAt, updatedAt, ...

FILTERING RULES (Applied during load)
======================================
At load time, we filter repos by:
  - NOT archived (isArchived = false)
  - NOT a fork (isFork = false)
  - Minimum commits (per config)
  - Minimum stars (per config)
  - NOT in EXCLUSION_KEYWORDS (tutorial, homework, etc.)
"""

import gzip
import csv
import json
import logging
from pathlib import Path
from contextlib import contextmanager

from collection.config import (
    LANGUAGE_CONFIGS,
    EXCLUSION_KEYWORDS,
    LanguageConfig,
    star_tier,
    MIN_COMMITS,
)
from collection.db import db_session, upsert_repository

logger = logging.getLogger(__name__)

# GHS export directory
GITHUB_SEARCH_DIR = Path(__file__).parent.parent / "github-search"


# ---------------------------------------------------------------------------
# CSV Loading
# ---------------------------------------------------------------------------


def _parse_seart_ghs_repo(row: dict) -> dict:
    """
    Convert a SEART-GHS CSV row to the internal repo format.

    Args:
        row: Dictionary with keys from SEART-GHS CSV (id, name, stargazers, ...).

    Returns:
        Dictionary with keys matching collection.db expectations
        (github_id, full_name, language, stars, forks, ...).
    """
    # Extract owner/repo from SEART-GHS "name" field
    # (e.g., "pytest-dev/pytest" → full_name, or similar)
    full_name = row.get("name", "")

    return {
        "github_id": int(row["id"]),
        "full_name": full_name,
        "language": row.get("mainLanguage", "").lower(),
        "stars": int(row.get("stargazers", 0)),
        "forks": int(row.get("forks", 0)),
        "description": row.get("description", "") or "",
        "topics": json.dumps(
            row.get("topics", "").split(";") if row.get("topics") else []
        ),
        "created_at": row.get("createdAt", ""),
        "pushed_at": row.get("pushedAt", ""),
        "clone_url": f"https://github.com/{full_name}.git",
        "star_tier": star_tier(int(row.get("stargazers", 0))),
    }


def _is_excluded(repo: dict, config: LanguageConfig) -> tuple[bool, str]:
    """
    Returns (should_exclude, reason).
    Checks against SEART-GHS repo data.
    """
    name = (repo.get("name") or "").lower()
    description = (repo.get("description") or "").lower()
    text = f"{name} {description}"

    for kw in config.exclusion_keywords:
        if kw in text:
            return True, f"exclusion keyword '{kw}'"

    if repo.get("isArchived"):
        return True, "is archived"

    if repo.get("isFork"):
        return True, "is a fork"

    return False, ""


def _load_csv_gz(file_path: Path) -> list[dict]:
    """Load and parse a gzip-compressed CSV file."""
    repos = []
    try:
        with gzip.open(file_path, "rt", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                # Data type conversions from CSV strings
                row["stargazers"] = int(float(row.get("stargazers", 0)))
                row["commits"] = int(float(row.get("commits", 0)))
                row["isFork"] = row.get("isFork", "false").lower() == "true"
                row["isArchived"] = row.get("isArchived", "false").lower() == "true"
                repos.append(row)
        logger.info(f"Loaded {len(repos)} repos from {file_path.name}")
        return repos
    except FileNotFoundError:
        logger.error(f"File not found: {file_path}")
        return []
    except Exception as e:
        logger.error(f"Error reading {file_path}: {e}")
        return []


# ---------------------------------------------------------------------------
# Main loading function
# ---------------------------------------------------------------------------


def load_repos_for_language(language_key: str) -> int:
    """
    Load pre-scraped repos from SEART-GHS CSV and persist them to the database.
    Returns the number of NEW repos written.

    Repos already in the database are skipped for counting purposes
    (their metadata is updated in place).

    **Note**: All repos from the CSV that pass basic quality filters (archived,
    forks, keywords, min stars/commits) are loaded. The 500-per-language target
    is enforced at the clone/analyze phase, not here. Some repos loaded here
    will be filtered out later if they lack test files or test fixtures.

    Args:
        language_key: Language to load (e.g., 'python', 'java', 'javascript', 'typescript')

    Returns:
        Number of newly inserted repositories
    """
    if language_key not in LANGUAGE_CONFIGS:
        logger.error(f"Unknown language '{language_key}'")
        return 0

    config = LANGUAGE_CONFIGS[language_key]

    # Map language_key to expected CSV filename
    # (python → python-results.csv.gz, etc.)
    csv_file = GITHUB_SEARCH_DIR / f"{language_key}-results.csv.gz"

    if not csv_file.exists():
        logger.error(f"SEART-GHS CSV not found: {csv_file}")
        logger.info(
            f"Please download {csv_file.name} from https://seart-ghs.si.usi.ch/"
        )
        return 0

    # Load all repos from CSV
    raw_repos = _load_csv_gz(csv_file)
    if not raw_repos:
        return 0

    logger.info(f"Processing {len(raw_repos)} repos for {language_key}...")

    # Filter and insert
    count_new = 0
    count_excluded = 0
    count_skipped = 0

    with db_session() as conn:
        for repo in raw_repos:
            # Apply quality filters
            is_excluded, reason = _is_excluded(repo, config)
            if is_excluded:
                count_excluded += 1
                continue

            # Check minimum commits threshold
            commits = int(repo.get("commits", 0))
            if commits < MIN_COMMITS:
                count_skipped += 1
                continue

            # Convert to internal format
            internal_repo = _parse_seart_ghs_repo(repo)

            # Upsert to database
            _, is_new = upsert_repository(conn, internal_repo)
            if is_new:
                count_new += 1

    logger.info(
        f"✓ Loaded {count_new} new repos for {language_key} "
        f"({count_excluded} excluded, {count_skipped} below commit threshold)"
    )
    return count_new


def load_all_languages() -> dict[str, int]:
    """
    Load repos for all configured languages from CSV files.
    
    All repos that pass basic quality filters are loaded into the database.
    The 500-per-language target is enforced at the clone/analyze phase,
    not during loading. This allows downstream processing to filter based on
    actual test file presence and fixture extraction results.

    Returns:
        Dictionary mapping language names to count of newly loaded repos.
    """
    results = {}
    for language_key in LANGUAGE_CONFIGS.keys():
        count = load_repos_for_language(language_key)
        results[language_key] = count
    return results
